### ISSUE TITLE
error authenticating

### ISSUE THREAD

**Issue by starascendin** [kotolex/surrealist#54]
first of all, thx for making this lib and it is delightful to use it.

So i've updated to the latest for Sdb 2.0, and i've been running issues regarding authentication with the following:

```
db = Database(url, ns, dbname, credentials=credentials)
```

and i had to change it to this to work
```
   url="http://127.0.0.1:8089/", ns="bashar", dbname="bashar", credentials=("root", "root")):
    try:
        db = Database(url, ns, dbname)
        print('is_connected', db.is_connected())
        conn = db.get_connection() 
        conn._signin(credentials[0], credentials[1])
    
``

**Comment by kotolex** [comment]
@starascendin , hey!
Can u provide more details about issue? What error u get in first case?
DO u try from connect [examples](https://github.com/kotolex/surrealist/blob/master/examples/connect.py)? 
`
# Note 2: to use root or namespace user for Database, you can use connection, but before switch to db level
surreal = Surreal("http://127.0.0.1:8000", credentials=("root", "root"))
with surreal.connect() as ws_connection:
    ws_connection.use("test", "test")
    db = Database.from_connection(ws_connection)

`

**Comment by starascendin** [comment]
Hi, it seems like this is an issue on my and I re-tried the orm this time and it works. Will close this. Thank you for your work on this!!!
