### ISSUE TITLE
whats the right way to do datetime?

### ISSUE THREAD

**Issue by starascendin** [kotolex/surrealist#58]
hi, first of all, thanks for your work, i love this lib you put out.

Issue im facing is datetime types like:

```
    tm = to_surreal_datetime_str(datetime.now(timezone.utc))  # get current time in surreal format
    result = table.create().content({'name': "xxx", 'age': 22, 'active': True,
                                    #  'create_time':f'd"{tm}"'
                                    # "create_time": "d'2024-10-01T13:30:45.157235467Z'"
                                    'create_time': "d'2024-10-03T13:30:45.157Z"
                                    # 'create_time':'d"2024-10-22T13:30:45.157235467Z"'
                                     }).run()  # dict now


Found "d'2024-10-03T13:30:45.157Z" for field `create_time`, with record `z_person:u1j108imaw0gzwwbusbb`, but expected a datetime

Found '2024-10-22T13:54:40.445833Z' for field `create_time`, with record `z_person:p8vji2zhvr8z7frhsaex`, but expected a datetime
```
whats the right way to do datetime? With the surreal's python sdk, i have to prefix a `d` in front of the datetime str

this is for surreal2.0

**Comment by kotolex** [comment]
Hey, @starascendin !
Why do u add "d" to datetime? for 2.0 surreal it works fine without it
`
tm = to_surreal_datetime_str(datetime.now(timezone.utc))  # get current time in surreal format
    result = db.some_table.create().content({'name': "xxx", 'age': 22, 'active': True, 'create_time': tm}).run()
    print(result) 
    for record in db.some_table.select().run().result:
        print(record)
`
 In results

`{'active': True, 'age': 22, 'create_time': '2024-10-22T16:18:59.367084Z', 'id': 'some_table:4ooq0l58phrds0yl77wa', 'name': 'xxx'}
{'active': True, 'age': 22, 'create_time': '2024-10-22T16:20:19.537789Z', 'id': 'some_table:durn37792lcan3ox31bq', 'name': 'xxx'}
{'active': True, 'age': 22, 'create_time': '2024-10-22T16:20:08.007334Z', 'id': 'some_table:dyebjtviku93374i46g9', 'name': 'xxx'}`

**Comment by starascendin** [comment]
does it still work if you have datetime type on the create_time field, like
```
DEFINE FIELD create_time ON z_person TYPE datetime DEFAULT time::now() PERMISSIONS FULL;
DEFINE FIELD update_time ON z_person TYPE datetime DEFAULT time::now() PERMISSIONS FULL;
```
based on surreal 2.0, they dont do auto type conversion for dates anymore. So in surrealist, i have to add d prefix to str to make it work; otherwise it fails. 

Is this something you are getting? 


## works
![CleanShot 2024-10-23 at 11 34 34@2x](https://github.com/user-attachments/assets/f2f4af1d-1e87-4d50-a0ab-014005c36481)


## doesnt work
![CleanShot 2024-10-23 at 11 33 16@2x](https://github.com/user-attachments/assets/2f440aba-3981-4256-87c0-fad367dccd3a)
![CleanShot 2024-10-23 at 11 33 49@2x](https://github.com/user-attachments/assets/91a91c62-4b40-4111-a701-6427020e840a)

**Comment by kotolex** [comment]
@starascendin yes, u right, if FIELD is explicit datetime format - I get an error back. Hmmm... need time to discuss with SDB developers how to properly sends d"some_datetime" via json

**Comment by starascendin** [comment]
FYI
so this also happens w/ surrealdb's python sdk, which is like 1 year stale. They said they are gonna update it eventually.

This doesnt happen w/ their JS sdk, but only works w/ new Date() object, or add a d prefix to the string.

Hope this helps!

**Comment by kotolex** [comment]
@starascendin please update to new version (1.0.3)

now function `to_surreal_datetime_str(datetime.now(timezone.utc))` returns string with d-prefix d'2024-02-06T12:25:48.700483Z'

So, all u need now to work with datetime fields is to create string with d-prefix yourself or (better) use to_surreal_datetime_str

now example works fine even if  field was defined as datetime
```python
tm = to_surreal_datetime_str(datetime.now(timezone.utc))  # get current time in surreal format
result = db.some_table.create().content({'name': "xxx", 'age': 22, 'active': True, 'create_time': tm}).run()
print(result) 
``` 

I added tests for it, examples and block in Readme
please, check it works for you

And again -I am really appreciate your help!

**Comment by starascendin** [comment]
that worked!! 

thanks for your work on this, you are awesome! I'll go ahead and close this issue
